[package]
name = "scylla"
version = "0.1.0"
edition = "2024"

[lib]
name = "scylla"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.25.1", features = ["extension-module", "experimental-async"] }
scylla = {git = "https://github.com/jakub-graczyk/scylla-rust-driver.git", branch = "python-driver-prototype"}
scylla-cql = {git = "https://github.com/jakub-graczyk/scylla-rust-driver.git", branch = "python-driver-prototype"}
tokio = { version = "1.42.0", features = ["full"] }
