[package]
name = "scylla"
version = "0.1.0"
edition = "2024"

[lib]
name = "scylla"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.25.1", features = ["extension-module", "experimental-async"] }
scylla = {path = "../scylla-rust-driver/scylla"}
scylla-cql = {path = "../scylla-rust-driver/scylla-cql"}
tokio = { version = "1.42.0", features = ["full"] }
