[package]
name = "scylla"
version = "0.1.0"
edition = "2024"

[lib]
name = "scylla"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.27.2", features = ["extension-module", "experimental-async"] }
scylla = "1.3.1"
tokio = { version = "1.42.0", features = ["full"] }
