[package]
name = "scylla"
version = "0.1.0"
edition = "2024"

[lib]
name = "scylla"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.27.2", features = ["extension-module", "experimental-async"] }
tokio = { version = "1.42.0", features = ["full"] }
scylla = { git = "https://github.com/scylladb-zpp-2025-python-rs-driver/scylla-rust-driver"}
scylla-cql = { git = "https://github.com/scylladb-zpp-2025-python-rs-driver/scylla-rust-driver"}

yoke = "0.8.1"
stable_deref_trait = "1.2"

